### ISSUE TITLE
Is there a way to save these images to memory?

### ISSUE THREAD

**Issue by miaawong** [iberatkaya/image-augmentation#2]
Can these images be augmented for real-time augmentation during training? I am training on the browser using tfjs, I want to augment these images without downloading them. Thanks!

**Comment by iberatkaya** [comment]
No, unfortunately these images cannot be augmented in real-time. Also this package uses [sharp](https://www.npmjs.com/package/sharp) for the image manipulation, which is only available on Node.js. It will not work on your browser.
